require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - tmp/**/*
    - bin/**/*
    - db/schema.rb
    - db/migrate/*


GlobalVars:
  AllowedVariables:
    - $puma_worker

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Max: 40
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 15

Lint/EmptyBlock:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

